# Generated by Django 2.2.2 on 2019-06-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20190613_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='tipo',
            field=models.CharField(choices=[('a', 'Admin'), ('v', 'Vendedor')], max_length=20),
        ),
    ]
