# Generated by Django 2.2.2 on 2019-06-13 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coche',
            name='modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coches.Modelo'),
        ),
    ]
