# Generated by Django 2.2.2 on 2019-06-13 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coches', '0002_auto_20190613_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coche',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Cliente'),
        ),
    ]
