# Generated by Django 2.2.2 on 2019-06-13 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_auto_20190613_1612'),
        ('coches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.IntegerField(choices=[(1, 'Pagado'), (2, 'Confirmando Pago'), (3, 'Cancelado')])),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Cliente')),
                ('coche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coches.Coche')),
            ],
        ),
    ]
